from django.db import models

class Users(models.Model):
    username = models.CharField(max_length=15, unique=True)
    email = models.EmailField(max_length=70, unique=True)
    password = models.CharField(max_length=50)

class Recipes(models.Model):
    title = models.CharField(max_length=50)
    rating = models.FloatField()
    apple = models.CharField(max_length=10, blank=True)
    rice = models.CharField(max_length=10, blank=True)
    tomato = models.CharField(max_length=10, blank=True)
    onion = models.CharField(max_length=10, blank=True)
    orange = models.CharField(max_length=10, blank=True)
    tea = models.CharField(max_length=10, blank=True)
    chocolate = models.CharField(max_length=10, blank=True)
    egg = models.CharField(max_length=10,blank=True)
    lentil = models.CharField(max_length=10,blank=True)
    potato = models.CharField(max_length=10,blank=True)
    lemon = models.CharField(max_length=10,blank=True)
    garlic = models.CharField(max_length=10,blank=True)
    strawberry = models.CharField(max_length=10,blank=True)
    vegan = models.CharField(max_length=10,blank=True)
    poultry = models.CharField(max_length=10,blank=True)
    organic = models.CharField(max_length=10,blank=True)
    no_cook = models.CharField(max_length=10,blank=True)
    no_sugar = models.CharField(max_length=10,blank=True)
    lunch = models.CharField(max_length=10,blank=True)
    high_fiber = models.CharField(max_length=10,blank=True)
    healthy = models.CharField(max_length=10,blank=True)
    grill = models.CharField(max_length=10,blank=True)
    dinner = models.CharField(max_length=10,blank=True)
    dairy_free = models.CharField(max_length=10,blank=True)
    meal_22_minutes = models.CharField(max_length=10,blank=True)
    appetizer = models.CharField(max_length=10,blank=True)


class User_Preferences(models.Model):
    username = models.CharField(max_length=50)
    vegan = models.CharField(max_length=10, blank=True)
    poultry = models.CharField(max_length=10, blank=True)
    organic = models.CharField(max_length=10, blank=True)
    no_cook = models.CharField(max_length=10,blank=True)
    no_sugar = models.CharField(max_length=10,blank=True)
    lunch = models.CharField(max_length=10,blank=True)
    high_fiber = models.CharField(max_length=10,blank=True)
    healthy = models.CharField(max_length=10,blank=True)
    grill = models.CharField(max_length=10,blank=True)
    dinner = models.CharField(max_length=10,blank=True)
    dairy_free = models.CharField(max_length=10,blank=True)
    meal_22_minutes = models.CharField(max_length=10,blank=True)
    appetizer = models.CharField(max_length=10,blank=True)
 
class User_Groceries(models.Model):
    username = models.CharField(max_length=50)
    apple = models.CharField(max_length=10,blank=True)
    rice = models.CharField(max_length=10,blank=True)
    tomato = models.CharField(max_length=10,blank=True)
    onion = models.CharField(max_length=10,blank=True)
    orange = models.CharField(max_length=10,blank=True)
    tea = models.CharField(max_length=10,blank=True)
    chocolate = models.CharField(max_length=10,blank=True)
    egg = models.CharField(max_length=10,blank=True)
    lentil = models.CharField(max_length=10,blank=True)
    potato = models.CharField(max_length=10,blank=True)
    lemon = models.CharField(max_length=10,blank=True)
    garlic = models.CharField(max_length=10,blank=True)
    strawberry = models.CharField(max_length=10,blank=True)

class Login_logs(models.Model):
    username = models.CharField(max_length=50)
    datetime = models.DateTimeField(auto_now_add=True)