# Generated by Django 2.1.3 on 2018-12-23 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login_logs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('rating', models.FloatField()),
                ('apple', models.CharField(max_length=10)),
                ('rice', models.CharField(max_length=10)),
                ('tomato', models.CharField(max_length=10)),
                ('onion', models.CharField(max_length=10)),
                ('orange', models.CharField(max_length=10)),
                ('tea', models.CharField(max_length=10)),
                ('chocolate', models.CharField(max_length=10)),
                ('egg', models.CharField(max_length=10)),
                ('lentil', models.CharField(max_length=10)),
                ('potato', models.CharField(max_length=10)),
                ('lemon', models.CharField(max_length=10)),
                ('garlic', models.CharField(max_length=10)),
                ('starwberry', models.CharField(max_length=10)),
                ('vegan', models.CharField(max_length=10)),
                ('poulty', models.CharField(max_length=10)),
                ('organic', models.CharField(max_length=10)),
                ('no_cook', models.CharField(max_length=10)),
                ('no_sugar', models.CharField(max_length=10)),
                ('lunch', models.CharField(max_length=10)),
                ('high_fiber', models.CharField(max_length=10)),
                ('healthy', models.CharField(max_length=10)),
                ('grill', models.CharField(max_length=10)),
                ('dinner', models.CharField(max_length=10)),
                ('dairy_free', models.CharField(max_length=10)),
                ('meal_22_minutes', models.CharField(max_length=10)),
                ('appetizer', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='User_Groceries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('apple', models.CharField(max_length=10)),
                ('rice', models.CharField(max_length=10)),
                ('tomato', models.CharField(max_length=10)),
                ('onion', models.CharField(max_length=10)),
                ('orange', models.CharField(max_length=10)),
                ('tea', models.CharField(max_length=10)),
                ('chocolate', models.CharField(max_length=10)),
                ('egg', models.CharField(max_length=10)),
                ('lentil', models.CharField(max_length=10)),
                ('potato', models.CharField(max_length=10)),
                ('lemon', models.CharField(max_length=10)),
                ('garlic', models.CharField(max_length=10)),
                ('starwberry', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='User_Preferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('vegan', models.CharField(max_length=10)),
                ('poulty', models.CharField(max_length=10)),
                ('organic', models.CharField(max_length=10)),
                ('no_cook', models.CharField(max_length=10)),
                ('no_sugar', models.CharField(max_length=10)),
                ('lunch', models.CharField(max_length=10)),
                ('high_fiber', models.CharField(max_length=10)),
                ('healthy', models.CharField(max_length=10)),
                ('grill', models.CharField(max_length=10)),
                ('dinner', models.CharField(max_length=10)),
                ('dairy_free', models.CharField(max_length=10)),
                ('meal_22_minutes', models.CharField(max_length=10)),
                ('appetizer', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(max_length=70, unique=True)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
