# Generated by Django 2.1.3 on 2018-12-23 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipefyApp', '0002_auto_20181223_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='appetizer',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='apple',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='chocolate',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='dairy_free',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='dinner',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='egg',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='garlic',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='grill',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='healthy',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='high_fiber',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='lemon',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='lentil',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='lunch',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='meal_22_minutes',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='no_cook',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='no_sugar',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='onion',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='orange',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='organic',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='potato',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='poultry',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='rice',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='starwberry',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='tea',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='tomato',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='vegan',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
