# Generated by Django 2.1.3 on 2018-12-23 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipefyApp', '0003_auto_20181223_1720'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipes',
            old_name='starwberry',
            new_name='strawberry',
        ),
    ]
